import code as x 
x.create("rattj",25)
x.create("src",70,3600) 
x.read("rattj")
x.read("src")
x.create("rattj",50)
x.modify("rattj",55) 
x.delete("rattj")
t1=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t1.start()
t1.sleep()
t2=Thread(target=(create or read or delete),args=(key_name,value,timeout)) 
t2.start()
t2.sleep()
